-- ログインマスタテーブル定義
CREATE TABLE M001(
    LOGINID CHARACTER VARYING(8),    -- ログインＩＤ
    LOGINPW CHARACTER VARYING(8),    -- ログインPW
    KAISYAMEI CHARACTER VARYING(24), -- 会社名
    ROLE01 CHARACTER VARYING(250),   -- ロール１
    ROLE02 CHARACTER VARYING(250),   -- ロール２
    ROLE03 CHARACTER VARYING(250),   -- ロール３
    PRIMARY KEY (LOGINID, LOGINPW)
);